name: Android Build CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :QTool:assembleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        # don't upload the artifacts if it's a pull request
        if: ${{ !github.event.pull_request }}
        with:
          path: 'QTool/build/outputs/apk/release/*.apk'
          name: QAuxiliary-release-${{ github.event.head_commit.id }}